<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    //通用
    'goback'=>'返回',
    'name'=>'名称',
    'link'=>'链接',
    'description'=>'描述',
    'status'=>'状态',
    'icon'=>'图标(需手动加icon-前缀)',
    'close'=>'关闭',
    'save'=>'保存',
    'reset'=>'重置',
    'cancel'=>'取消',
    'create'=>'添加',
    'operation'=>'操作',
    'update'=>'编辑',
    'delete'=>'删除',
    'deny'=>'您无权限进行该操作，请联系管理员！',
    'error.load.data'=>'获取请求数据错误',
    'error.insert'=>'添加失败',
    'error.delete'=>'删除失败',
    'gridtable.norecords'=>'共有0条记录',
    'gridtable.pages.title'=>'当前显示{start}至{end}条记录&nbsp;共有{total}条记录',
    'login.title'=>'欢迎登录后台管理',
    'login.failed'=>'登录失败',
    'login.success'=>'登录成功',
    'login.username'=>'用户名',
    'login.password'=>'密码',
    'login.submit'=>'登陆',
    'login.rememberme'=>'记住我',
    'status.ok'=>'有效',
    'status.no'=>'无效',
    'navigation'=>'设置为导航',
    'yes'=>'是',
    'no'=>'否',
    //首页
    'index'=>'首页',
    'index.title'=>'首页范例',
    'index.dashboard'=>'仪表盘',
    //尾部
    'footer.copyright'=>'2015 &copy; Admin Template By liupeng.',
    //个人页
    'user.info'=>'个人信息',
    'user.logout'=>'退出',
    //权限
    'perm.title'=>'权限管理',
    'perm.list.title'=>'权限列表',
    'perm.seq.title'=>'调整顺序',
    'error.perm.parent.notexists'=>'父级权限不存在',
    'error.perm.notexists'=>'权限不存在',
    'error.perm.root.delete'=>'Root节点不能删除',
    'error.perm.noeditable'=>'该节点不允许编辑',
    'error.perm.level.max'=>'已超过最大节点树',
    //角色
    'role.title'=>'角色管理',
    'role.list.title'=>'角色列表',
    'role.perm.title'=>'设置权限',
    'role.perm.owner'=>'拥有权限',
    'error.role.notexists'=>'角色不存在',
    'error.role.power.edit'=>'超级管理员不能编辑',
     //角色
    'user.title'=>'用户管理',
    'user.list.title'=>'用户列表',
    'user.username'=>'用户名',
    'user.password'=>'密码',
    'user.name'=>'姓名',
    'error.user.notexists'=>'用户不存在',
    'error.admin.disabled'=>'admin用户不能禁用',
    'error.admin.onlyedit'=>'您无权限编辑admin用户信息',

];
