<?php
/**
 * Author: liupeng
 * Date: 2015/7/11
 */

namespace liuxy\admin\widgets;

use liuxy\admin\components\helpers\Html;
use liuxy\admin\assets\plugins\jquery\ICheckAsset;


/**
 * 复选框
 * Class Checkbox
 *
 * @package liuxy\themes\admin\widgets
 */
class Checkbox extends Widget {

    /**
     * 复选框的元素标签
     * @var string
     */
    public $label = null;
    /**
     * 标签属性配置
     * @var array
     */
    public $labelOptions = ['class' => 'control-label'];

    public $options = ['class'=>'input-group'];

    /**
     * 元素名称
     * @var string
     */
    public $name = null;

    /**
     * 所有值数组，value:label
     * @var array
     */
    public $items = [];

    /**
     * 需要选中的值列表
     * @var mixed
     */
    public $values = [];

    /**
     * 样式风格，可选：minimal、square、flat、line
     * @var string
     */
    public $style = 'flat';

    /**
     * 颜色
     * @var string，可选：空值、red、green、aero、grey、orange、pink、purple
     */
    public $color = 'green';

    /**
     * 设置是否横向排列，默认是
     * @var bool
     */
    public $inline = true;

    /**
     * @inheritDoc
     */
    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
        $view = $this->getView();
        ICheckAsset::register($view);
    }


    /**
     * (non-PHPdoc)
     * @see \yii\base\Widget::run()
     */
    public function run() {
        $content = '';
        if ($this->label) {
            if (isset($this->labelOptions['class'])) {
                $this->labelOptions['class'] = 'control-label '.$this->labelOptions['class'];
            } else {
                Html::addCssClass($this->labelOptions,'col-md-4');
            }
            $content.=Html::tag('label',$this->label,$this->labelOptions);
        }
        $content.=Html::beginTag('div',$this->options);
        $content.=Html::beginTag('div',['id'=>$this->name.'-group','class'=>$this->inline ? 'icheck-inline' : 'icheck-list']);
        if ($this->items) {
            foreach($this->items as $value=>$label) {
                $content.=Html::beginTag('label');
                $content.= $this->renderContent($value);
                $content.="\n" . $label . "\n";
                $content.=Html::endTag('label');
            }
        }
        $content.=Html::endTag('div');
        $content.=Html::endTag('div');
        echo Html::tag('div', $content, ['class'=>'form-group']);
    }

    /**
     * 渲染checkbox
     * @param $value    元素值
     * @return string   dom元素
     */
    protected function renderContent($value) {
        return Html::checkbox($this->name.'['.$value.']', in_array($value, $this->values), ['class'=>'icheck','data-checkbox'=>'icheckbox_'.$this->style.'-'.$this->color,'value'=>$value]);
    }
}